FROM node:18.17-alpine

WORKDIR /app

ARG ENVIRONMENT

COPY ./ ./

RUN yarn --frozen-lockfile

RUN yarn sandbox:build:ssr:$ENVIRONMENT
# # RUN ng run atomik:prerender:$ENVIRONMENT



CMD ["npm", "run", "sandbox:serve:ssr"]
